// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: estategap/v1/ai_chat.proto

package estategapv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

const (
	AIChatService_Chat_FullMethodName              = "/estategap.v1.AIChatService/Chat"
	AIChatService_GetConversation_FullMethodName   = "/estategap.v1.AIChatService/GetConversation"
	AIChatService_ListConversations_FullMethodName = "/estategap.v1.AIChatService/ListConversations"
)

type AIChatServiceClient interface {
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error)
	GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error)
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
}

type aIChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIChatServiceClient(cc grpc.ClientConnInterface) AIChatServiceClient {
	return &aIChatServiceClient{cc}
}

func (c *aIChatServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[0], AIChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	return &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}, nil
}

func (c *aIChatServiceClient) GetConversation(ctx context.Context, in *GetConversationRequest, opts ...grpc.CallOption) (*GetConversationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResponse)
	if err := c.cc.Invoke(ctx, AIChatService_GetConversation_FullMethodName, in, out, cOpts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIChatServiceClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConversationsResponse)
	if err := c.cc.Invoke(ctx, AIChatService_ListConversations_FullMethodName, in, out, cOpts...); err != nil {
		return nil, err
	}
	return out, nil
}

type AIChatService_ChatClient = grpc.BidiStreamingClient[ChatRequest, ChatResponse]

type AIChatServiceServer interface {
	Chat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error
	GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error)
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	mustEmbedUnimplementedAIChatServiceServer()
}

type UnimplementedAIChatServiceServer struct{}

func (UnimplementedAIChatServiceServer) Chat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func (UnimplementedAIChatServiceServer) GetConversation(context.Context, *GetConversationRequest) (*GetConversationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversation not implemented")
}

func (UnimplementedAIChatServiceServer) ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConversations not implemented")
}

func (UnimplementedAIChatServiceServer) mustEmbedUnimplementedAIChatServiceServer() {}
func (UnimplementedAIChatServiceServer) testEmbeddedByValue()                       {}

type UnsafeAIChatServiceServer interface {
	mustEmbedUnimplementedAIChatServiceServer()
}

func RegisterAIChatServiceServer(s grpc.ServiceRegistrar, srv AIChatServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIChatService_ServiceDesc, srv)
}

func _AIChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AIChatServiceServer).Chat(&grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

func _AIChatService_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIChatServiceServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIChatService_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIChatServiceServer).GetConversation(ctx, req.(*GetConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIChatService_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIChatServiceServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIChatService_ListConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIChatServiceServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

type AIChatService_ChatServer = grpc.BidiStreamingServer[ChatRequest, ChatResponse]

var AIChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "estategap.v1.AIChatService",
	HandlerType: (*AIChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversation",
			Handler:    _AIChatService_GetConversation_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _AIChatService_ListConversations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIChatService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "estategap/v1/ai_chat.proto",
}
