// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: estategap/v1/ml_scoring.proto

package estategapv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const (
	MLScoringService_ScoreListing_FullMethodName   = "/estategap.v1.MLScoringService/ScoreListing"
	MLScoringService_ScoreBatch_FullMethodName     = "/estategap.v1.MLScoringService/ScoreBatch"
	MLScoringService_GetComparables_FullMethodName = "/estategap.v1.MLScoringService/GetComparables"
)

type MLScoringServiceClient interface {
	ScoreListing(ctx context.Context, in *ScoreListingRequest, opts ...grpc.CallOption) (*ScoreListingResponse, error)
	ScoreBatch(ctx context.Context, in *ScoreBatchRequest, opts ...grpc.CallOption) (*ScoreBatchResponse, error)
	GetComparables(ctx context.Context, in *GetComparablesRequest, opts ...grpc.CallOption) (*GetComparablesResponse, error)
}

type mLScoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLScoringServiceClient(cc grpc.ClientConnInterface) MLScoringServiceClient {
	return &mLScoringServiceClient{cc}
}

func (c *mLScoringServiceClient) ScoreListing(ctx context.Context, in *ScoreListingRequest, opts ...grpc.CallOption) (*ScoreListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreListingResponse)
	if err := c.cc.Invoke(ctx, MLScoringService_ScoreListing_FullMethodName, in, out, cOpts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLScoringServiceClient) ScoreBatch(ctx context.Context, in *ScoreBatchRequest, opts ...grpc.CallOption) (*ScoreBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScoreBatchResponse)
	if err := c.cc.Invoke(ctx, MLScoringService_ScoreBatch_FullMethodName, in, out, cOpts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLScoringServiceClient) GetComparables(ctx context.Context, in *GetComparablesRequest, opts ...grpc.CallOption) (*GetComparablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComparablesResponse)
	if err := c.cc.Invoke(ctx, MLScoringService_GetComparables_FullMethodName, in, out, cOpts...); err != nil {
		return nil, err
	}
	return out, nil
}

type MLScoringServiceServer interface {
	ScoreListing(context.Context, *ScoreListingRequest) (*ScoreListingResponse, error)
	ScoreBatch(context.Context, *ScoreBatchRequest) (*ScoreBatchResponse, error)
	GetComparables(context.Context, *GetComparablesRequest) (*GetComparablesResponse, error)
	mustEmbedUnimplementedMLScoringServiceServer()
}

type UnimplementedMLScoringServiceServer struct{}

func (UnimplementedMLScoringServiceServer) ScoreListing(context.Context, *ScoreListingRequest) (*ScoreListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreListing not implemented")
}

func (UnimplementedMLScoringServiceServer) ScoreBatch(context.Context, *ScoreBatchRequest) (*ScoreBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScoreBatch not implemented")
}

func (UnimplementedMLScoringServiceServer) GetComparables(context.Context, *GetComparablesRequest) (*GetComparablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComparables not implemented")
}

func (UnimplementedMLScoringServiceServer) mustEmbedUnimplementedMLScoringServiceServer() {}
func (UnimplementedMLScoringServiceServer) testEmbeddedByValue()                          {}

type UnsafeMLScoringServiceServer interface {
	mustEmbedUnimplementedMLScoringServiceServer()
}

func RegisterMLScoringServiceServer(s grpc.ServiceRegistrar, srv MLScoringServiceServer) {
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLScoringService_ServiceDesc, srv)
}

func _MLScoringService_ScoreListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLScoringServiceServer).ScoreListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLScoringService_ScoreListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLScoringServiceServer).ScoreListing(ctx, req.(*ScoreListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLScoringService_ScoreBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScoreBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLScoringServiceServer).ScoreBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLScoringService_ScoreBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLScoringServiceServer).ScoreBatch(ctx, req.(*ScoreBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLScoringService_GetComparables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComparablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLScoringServiceServer).GetComparables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLScoringService_GetComparables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLScoringServiceServer).GetComparables(ctx, req.(*GetComparablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var MLScoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "estategap.v1.MLScoringService",
	HandlerType: (*MLScoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScoreListing",
			Handler:    _MLScoringService_ScoreListing_Handler,
		},
		{
			MethodName: "ScoreBatch",
			Handler:    _MLScoringService_ScoreBatch_Handler,
		},
		{
			MethodName: "GetComparables",
			Handler:    _MLScoringService_GetComparables_Handler,
		},
	},
	Metadata: "estategap/v1/ml_scoring.proto",
}
