# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estategap/v1/ai_chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'estategap/v1/ai_chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from estategap.v1 import common_pb2 as estategap_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65stategap/v1/ai_chat.proto\x12\x0c\x65stategap.v1\x1a\x19\x65stategap/v1/common.proto\"R\n\x0b\x43hatRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x14\n\x0cuser_message\x18\x02 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\"]\n\x0c\x43hatResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\t\x12\x10\n\x08is_final\x18\x03 \x01(\x08\x12\x13\n\x0blisting_ids\x18\x04 \x03(\t\"1\n\x16GetConversationRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\"\x8e\x01\n\x17GetConversationResponse\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12-\n\x05turns\x18\x02 \x03(\x0b\x32\x1e.estategap.v1.ConversationTurn\x12+\n\ncreated_at\x18\x03 \x01(\x0b\x32\x17.estategap.v1.Timestamp\"]\n\x10\x43onversationTurn\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12*\n\ttimestamp\x18\x03 \x01(\x0b\x32\x17.estategap.v1.Timestamp\"`\n\x18ListConversationsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x33\n\npagination\x18\x02 \x01(\x0b\x32\x1f.estategap.v1.PaginationRequest\"\x8b\x01\n\x19ListConversationsResponse\x12\x38\n\rconversations\x18\x01 \x03(\x0b\x32!.estategap.v1.ConversationSummary\x12\x34\n\npagination\x18\x02 \x01(\x0b\x32 .estategap.v1.PaginationResponse\"l\n\x13\x43onversationSummary\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0f\n\x07preview\x18\x02 \x01(\t\x12+\n\ncreated_at\x18\x03 \x01(\x0b\x32\x17.estategap.v1.Timestamp2\x98\x02\n\rAIChatService\x12\x41\n\x04\x43hat\x12\x19.estategap.v1.ChatRequest\x1a\x1a.estategap.v1.ChatResponse(\x01\x30\x01\x12^\n\x0fGetConversation\x12$.estategap.v1.GetConversationRequest\x1a%.estategap.v1.GetConversationResponse\x12\x64\n\x11ListConversations\x12&.estategap.v1.ListConversationsRequest\x1a\'.estategap.v1.ListConversationsResponseB:Z8github.com/estategap/libs/proto/estategap/v1;estategapv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estategap.v1.ai_chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/estategap/libs/proto/estategap/v1;estategapv1'
  _globals['_CHATREQUEST']._serialized_start=71
  _globals['_CHATREQUEST']._serialized_end=153
  _globals['_CHATRESPONSE']._serialized_start=155
  _globals['_CHATRESPONSE']._serialized_end=248
  _globals['_GETCONVERSATIONREQUEST']._serialized_start=250
  _globals['_GETCONVERSATIONREQUEST']._serialized_end=299
  _globals['_GETCONVERSATIONRESPONSE']._serialized_start=302
  _globals['_GETCONVERSATIONRESPONSE']._serialized_end=444
  _globals['_CONVERSATIONTURN']._serialized_start=446
  _globals['_CONVERSATIONTURN']._serialized_end=539
  _globals['_LISTCONVERSATIONSREQUEST']._serialized_start=541
  _globals['_LISTCONVERSATIONSREQUEST']._serialized_end=637
  _globals['_LISTCONVERSATIONSRESPONSE']._serialized_start=640
  _globals['_LISTCONVERSATIONSRESPONSE']._serialized_end=779
  _globals['_CONVERSATIONSUMMARY']._serialized_start=781
  _globals['_CONVERSATIONSUMMARY']._serialized_end=889
  _globals['_AICHATSERVICE']._serialized_start=892
  _globals['_AICHATSERVICE']._serialized_end=1172
# @@protoc_insertion_point(module_scope)
