# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from estategap.v1 import ai_chat_pb2 as estategap_dot_v1_dot_ai__chat__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in estategap/v1/ai_chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/estategap.v1.AIChatService/Chat',
                request_serializer=estategap_dot_v1_dot_ai__chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ai__chat__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GetConversation = channel.unary_unary(
                '/estategap.v1.AIChatService/GetConversation',
                request_serializer=estategap_dot_v1_dot_ai__chat__pb2.GetConversationRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ai__chat__pb2.GetConversationResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/estategap.v1.AIChatService/ListConversations',
                request_serializer=estategap_dot_v1_dot_ai__chat__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ai__chat__pb2.ListConversationsResponse.FromString,
                _registered_method=True)


class AIChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=estategap_dot_v1_dot_ai__chat__pb2.ChatRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ai__chat__pb2.ChatResponse.SerializeToString,
            ),
            'GetConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversation,
                    request_deserializer=estategap_dot_v1_dot_ai__chat__pb2.GetConversationRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ai__chat__pb2.GetConversationResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=estategap_dot_v1_dot_ai__chat__pb2.ListConversationsRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ai__chat__pb2.ListConversationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estategap.v1.AIChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estategap.v1.AIChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/estategap.v1.AIChatService/Chat',
            estategap_dot_v1_dot_ai__chat__pb2.ChatRequest.SerializeToString,
            estategap_dot_v1_dot_ai__chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.AIChatService/GetConversation',
            estategap_dot_v1_dot_ai__chat__pb2.GetConversationRequest.SerializeToString,
            estategap_dot_v1_dot_ai__chat__pb2.GetConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.AIChatService/ListConversations',
            estategap_dot_v1_dot_ai__chat__pb2.ListConversationsRequest.SerializeToString,
            estategap_dot_v1_dot_ai__chat__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
