# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estategap/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'estategap/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x65stategap/v1/common.proto\x12\x0c\x65stategap.v1\"\x1b\n\tTimestamp\x12\x0e\n\x06millis\x18\x01 \x01(\x03\"B\n\x05Money\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x03\x12\x15\n\rcurrency_code\x18\x02 \x01(\t\x12\x12\n\neur_amount\x18\x03 \x01(\x03\"/\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"4\n\x11PaginationRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"\\\n\x12PaginationResponse\x12\x13\n\x0btotal_count\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x10\n\x08has_next\x18\x04 \x01(\x08\x42:Z8github.com/estategap/libs/proto/estategap/v1;estategapv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estategap.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/estategap/libs/proto/estategap/v1;estategapv1'
  _globals['_TIMESTAMP']._serialized_start=43
  _globals['_TIMESTAMP']._serialized_end=70
  _globals['_MONEY']._serialized_start=72
  _globals['_MONEY']._serialized_end=138
  _globals['_GEOPOINT']._serialized_start=140
  _globals['_GEOPOINT']._serialized_end=187
  _globals['_PAGINATIONREQUEST']._serialized_start=189
  _globals['_PAGINATIONREQUEST']._serialized_end=241
  _globals['_PAGINATIONRESPONSE']._serialized_start=243
  _globals['_PAGINATIONRESPONSE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
