# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estategap/v1/listings.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'estategap/v1/listings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from estategap.v1 import common_pb2 as estategap_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65stategap/v1/listings.proto\x12\x0c\x65stategap.v1\x1a\x19\x65stategap/v1/common.proto\"\x89\x03\n\x07Listing\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tportal_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x03 \x01(\t\x12+\n\x06status\x18\x04 \x01(\x0e\x32\x1b.estategap.v1.ListingStatus\x12/\n\x0clisting_type\x18\x05 \x01(\x0e\x32\x19.estategap.v1.ListingType\x12\x31\n\rproperty_type\x18\x06 \x01(\x0e\x32\x1a.estategap.v1.PropertyType\x12\"\n\x05price\x18\x07 \x01(\x0b\x32\x13.estategap.v1.Money\x12\x10\n\x08\x61rea_sqm\x18\x08 \x01(\x02\x12(\n\x08location\x18\t \x01(\x0b\x32\x16.estategap.v1.GeoPoint\x12+\n\ncreated_at\x18\n \x01(\x0b\x32\x17.estategap.v1.Timestamp\x12+\n\nupdated_at\x18\x0b \x01(\x0b\x32\x17.estategap.v1.Timestamp*\x9c\x01\n\rListingStatus\x12\x1e\n\x1aLISTING_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15LISTING_STATUS_ACTIVE\x10\x01\x12\x17\n\x13LISTING_STATUS_SOLD\x10\x02\x12\x19\n\x15LISTING_STATUS_RENTED\x10\x03\x12\x1c\n\x18LISTING_STATUS_WITHDRAWN\x10\x04*Y\n\x0bListingType\x12\x1c\n\x18LISTING_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11LISTING_TYPE_SALE\x10\x01\x12\x15\n\x11LISTING_TYPE_RENT\x10\x02*\xa0\x01\n\x0cPropertyType\x12\x1d\n\x19PROPERTY_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19PROPERTY_TYPE_RESIDENTIAL\x10\x01\x12\x1c\n\x18PROPERTY_TYPE_COMMERCIAL\x10\x02\x12\x1c\n\x18PROPERTY_TYPE_INDUSTRIAL\x10\x03\x12\x16\n\x12PROPERTY_TYPE_LAND\x10\x04\x42:Z8github.com/estategap/libs/proto/estategap/v1;estategapv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estategap.v1.listings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/estategap/libs/proto/estategap/v1;estategapv1'
  _globals['_LISTINGSTATUS']._serialized_start=469
  _globals['_LISTINGSTATUS']._serialized_end=625
  _globals['_LISTINGTYPE']._serialized_start=627
  _globals['_LISTINGTYPE']._serialized_end=716
  _globals['_PROPERTYTYPE']._serialized_start=719
  _globals['_PROPERTYTYPE']._serialized_end=879
  _globals['_LISTING']._serialized_start=73
  _globals['_LISTING']._serialized_end=466
# @@protoc_insertion_point(module_scope)
