# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from estategap.v1 import ml_scoring_pb2 as estategap_dot_v1_dot_ml__scoring__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in estategap/v1/ml_scoring_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLScoringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreListing = channel.unary_unary(
                '/estategap.v1.MLScoringService/ScoreListing',
                request_serializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingResponse.FromString,
                _registered_method=True)
        self.ScoreBatch = channel.unary_unary(
                '/estategap.v1.MLScoringService/ScoreBatch',
                request_serializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchResponse.FromString,
                _registered_method=True)
        self.GetComparables = channel.unary_unary(
                '/estategap.v1.MLScoringService/GetComparables',
                request_serializer=estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesResponse.FromString,
                _registered_method=True)


class MLScoringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScoreListing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScoreBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComparables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLScoringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreListing': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreListing,
                    request_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingResponse.SerializeToString,
            ),
            'ScoreBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreBatch,
                    request_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchResponse.SerializeToString,
            ),
            'GetComparables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComparables,
                    request_deserializer=estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estategap.v1.MLScoringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estategap.v1.MLScoringService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLScoringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScoreListing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.MLScoringService/ScoreListing',
            estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingRequest.SerializeToString,
            estategap_dot_v1_dot_ml__scoring__pb2.ScoreListingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScoreBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.MLScoringService/ScoreBatch',
            estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchRequest.SerializeToString,
            estategap_dot_v1_dot_ml__scoring__pb2.ScoreBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComparables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.MLScoringService/GetComparables',
            estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesRequest.SerializeToString,
            estategap_dot_v1_dot_ml__scoring__pb2.GetComparablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
