# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: estategap/v1/proxy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'estategap/v1/proxy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65stategap/v1/proxy.proto\x12\x0c\x65stategap.v1\":\n\x0fGetProxyRequest\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x11\n\tportal_id\x18\x02 \x01(\t\"7\n\x10GetProxyResponse\x12\x11\n\tproxy_url\x18\x01 \x01(\t\x12\x10\n\x08proxy_id\x18\x02 \x01(\t\"a\n\x13ReportResultRequest\x12\x10\n\x08proxy_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bstatus_code\x18\x03 \x01(\x05\x12\x12\n\nlatency_ms\x18\x04 \x01(\x03\",\n\x14ReportResultResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\xb0\x01\n\x0cProxyService\x12I\n\x08GetProxy\x12\x1d.estategap.v1.GetProxyRequest\x1a\x1e.estategap.v1.GetProxyResponse\x12U\n\x0cReportResult\x12!.estategap.v1.ReportResultRequest\x1a\".estategap.v1.ReportResultResponseB:Z8github.com/estategap/libs/proto/estategap/v1;estategapv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'estategap.v1.proxy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/estategap/libs/proto/estategap/v1;estategapv1'
  _globals['_GETPROXYREQUEST']._serialized_start=42
  _globals['_GETPROXYREQUEST']._serialized_end=100
  _globals['_GETPROXYRESPONSE']._serialized_start=102
  _globals['_GETPROXYRESPONSE']._serialized_end=157
  _globals['_REPORTRESULTREQUEST']._serialized_start=159
  _globals['_REPORTRESULTREQUEST']._serialized_end=256
  _globals['_REPORTRESULTRESPONSE']._serialized_start=258
  _globals['_REPORTRESULTRESPONSE']._serialized_end=302
  _globals['_PROXYSERVICE']._serialized_start=305
  _globals['_PROXYSERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
