# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from estategap.v1 import proxy_pb2 as estategap_dot_v1_dot_proxy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in estategap/v1/proxy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProxyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProxy = channel.unary_unary(
                '/estategap.v1.ProxyService/GetProxy',
                request_serializer=estategap_dot_v1_dot_proxy__pb2.GetProxyRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_proxy__pb2.GetProxyResponse.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/estategap.v1.ProxyService/ReportResult',
                request_serializer=estategap_dot_v1_dot_proxy__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=estategap_dot_v1_dot_proxy__pb2.ReportResultResponse.FromString,
                _registered_method=True)


class ProxyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProxy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProxy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProxy,
                    request_deserializer=estategap_dot_v1_dot_proxy__pb2.GetProxyRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_proxy__pb2.GetProxyResponse.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=estategap_dot_v1_dot_proxy__pb2.ReportResultRequest.FromString,
                    response_serializer=estategap_dot_v1_dot_proxy__pb2.ReportResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'estategap.v1.ProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('estategap.v1.ProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProxyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProxy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.ProxyService/GetProxy',
            estategap_dot_v1_dot_proxy__pb2.GetProxyRequest.SerializeToString,
            estategap_dot_v1_dot_proxy__pb2.GetProxyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/estategap.v1.ProxyService/ReportResult',
            estategap_dot_v1_dot_proxy__pb2.ReportResultRequest.SerializeToString,
            estategap_dot_v1_dot_proxy__pb2.ReportResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
