{{- $service := index .Values.services "spider-workers" -}}
{{- if and $service.enabled $service.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: spider-workers-scaler
  namespace: estategap-scraping
  labels:
    {{- include "estategap.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: spider-workers
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: {{ $service.keda.minReplicas }}
  maxReplicaCount: {{ $service.keda.maxReplicas }}
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: {{ .Values.kafka.brokers | quote }}
        consumerGroup: {{ $service.keda.consumer | quote }}
        topic: {{ printf "%s%s" .Values.kafka.topicPrefix $service.keda.stream | quote }}
        lagThreshold: {{ $service.keda.lagThreshold | quote }}
        offsetResetPolicy: latest
{{- end }}
