{{- if .Values.components.postgresql.deploy }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: estategap-postgres-daily
  namespace: estategap-system
  labels:
    {{- include "estategap.labels" . | nindent 4 }}
spec:
  schedule: {{ dig "backup" "schedule" "0 2 * * *" .Values.postgresql | quote }}
  backupOwnerReference: self
  cluster:
    name: estategap-postgres
{{- end }}
